### ISSUE TITLE
Cache is not getting cleared

### ISSUE THREAD

**Issue by skast96** [Jaxelr/Nancy.RapidCache#2]
# Type of Issue

```
[x ] Bug.
[ ] Feature.
```
## Expected Behavior

Steps: 
1. return Response.AsText((string) json, "application/json").AsCacheable(DateTime.Now.AddSeconds(1));
2. now the cache should work for 1 second. 
3. I change something in the data for testing
4. I am getting back the changed data.

## Actual Behavior

Steps: 
1. return Response.AsText((string) json, "application/json").AsCacheable(DateTime.Now.AddSeconds(1));
2. now the cache should work for 1 second. 
3. I change something in the data for testing
4. I am getting back the same data as before.

## Steps to Reproduce the Problem
  1. Run it like in your example

## Specifications

  - Version: 0.1.2
  - Platform: .Net Core with Nancy 2.0.0-clinteastwood
  - Subsystem:

## Extra
I have Stateless Auth running for some requests that use caching, if thats the point of the issue.

**Comment by skast96** [comment]
My bad it is working actually I was not using UTC, but I got another request for you. It would be nice to have an other flag than _rapidCacheDisabled to make sure cache is still valid.

**Comment by Jaxelr** [comment]
You do bring a great point, the date should be on any kind formatted to UTC, instead of only on UTC. I'll add that fix today, look for a new version 0.1.4 in a few hours.

With regards to your question concerning a flag, the requests by default return a Header that shows it is from the Cache:

![image](https://user-images.githubusercontent.com/5913008/42891112-92e0cd28-8a7c-11e8-9bca-0f99e6a51767.png)

Which is not included on requests that arent cached.

![image](https://user-images.githubusercontent.com/5913008/42890668-63a6f506-8a7b-11e8-9e2f-383d56458bea.png)

**Comment by skast96** [comment]
Thank you for you answer. I might be a little annoying, but it would be nice to have a flag like a query parameter that says cacheValid = true or something like that.

**Comment by Jaxelr** [comment]
Ahhh, i see what you mean. You need a way to clear the cache for that specific key using a request.

**Comment by Jaxelr** [comment]
Im closing this since you added this feature on PR #3 . I'll be released sometime this weekend on 0.1.5.

**Comment by Jaxelr** [comment]
Just a heads up that i changed the name of the parameter to send from removeRapid to rapidCacheRemove, just to be a bit more consistent with the feature of rapidCacheDisabled which keeps the value on the cache but sends a request without using the cache.
